# -*- coding: utf-8 -*-
"""7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dGj6Ar4isfDQARrkUd2fiLjxqi0hpprr
"""

from math import pi

class Shape:

    def area(self):

        raise NotImplementedError("Этот метод должен быть переопределён в подклассе")

class Rectangle(Shape):

    def __init__(self, width, height):
        self.width = width
        self.height = height

    def area(self):
        return self.width * self.height

class Circle(Shape):

    def __init__(self, radius):
        self.radius = radius

    def area(self):
        return pi * self.radius**2

class Triangle(Shape):

    def __init__(self, base, height):
        self.base = base
        self.height = height

    def area(self):
        return 0.5 * self.base * self.height

class Square(Rectangle):

    def __init__(self, side):
        super().__init__(side, side)


shapes = [
    Rectangle(5, 10),
    Circle(7),
    Triangle(6, 8),
    Square(4)
]

for shape in shapes:
    print(f"Площадь {shape.__class__.__name__}: {shape.area():.2f}")