# -*- coding: utf-8 -*-
"""1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dGj6Ar4isfDQARrkUd2fiLjxqi0hpprr
"""

from math import sqrt, pi

figure = input("Выберите фигуру: ")

class Geom_Figur:
    if figure == '1':
      print("Длины сторон прямоугольника:")
      a = float(input("a = "))
      b = float(input("b = "))
      print("Площадь: %.2f" % (a * b))
    elif figure == '2':
      print("Длины стороны и высоты ромба:")
      a = float(input("a = "))
      h = float(input("h = "))
      print("Площадь: %.2f" % (a * h))
    elif figure == '3':
      r = float(input("Радиус круга R = "))
      print("Площадь: %.2f" % (pi * r ** 2))
    else:
      print("Ошибка ввода")


class longsquare(Geom_Figur):
    longsquare = "1"

class romb(Geom_Figur):
    romb = "2"

class circle(Geom_Figur):
    circle = "3"