# -*- coding: utf-8 -*-
"""1 Zadanie

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lME9ayOmT0J0TriKTPu_0sGYcO4lpuJQ
"""

a = int(input('Input number: '))
b = 10
c = 5



if a < 0:
 print ("-1")
else:
  numbers = [a,b,c]
  max_number = max(numbers)
  print(max_number)